# @LinkSharingRepository_HostAddress = http://localhost:5095
@LinkSharingRepository_HostAddress =https://cg-frontendmentor-link-sharing.azurewebsites.net/
###
GET {{LinkSharingRepository_HostAddress}}/platforms/
Accept: application/json

###
PUT {{LinkSharingRepository_HostAddress}}/platforms/update/
Content-Type: application/json

{
  "id": 2,
  "name": "You Tube",
  "icon": "icon-youtube.svg",
  "brandingColor": "#FF0000"
}

###
POST {{LinkSharingRepository_HostAddress}}/users/add
Content-Type: application/json

{
  "firstName": "Chris",
  "surname": "Gilliam",
  "password": "passowrd",
  "email": "chrisg@home.com"
}

###
DELETE {{LinkSharingRepository_HostAddress}}/users/delete
Content-Type: application/json

{
  "email": "chrisg@home.com",
  "password": "passowrd"
}
###