# @LinkSharingRepository_HostAddress = http://localhost:5095
@LinkSharingRepository_HostAddress =https://cg-frontendmentor-link-sharing.azurewebsites.net/
###
GET {{LinkSharingRepository_HostAddress}}/platforms/
Accept: application/json

###
PUT {{LinkSharingRepository_HostAddress}}/platforms/update/
Content-Type: application/json

{
  "id": 2,
  "name": "You Tube",
  "icon": "icon-youtube.svg",
  "brandingColor": "#FF0000"
}

###
POST {{LinkSharingRepository_HostAddress}}/users/add
Content-Type: application/json

{
  "firstName": "Bill",
  "surname": "Gates",
  "password": "password1",
  "email": "bill@microsoft.com"
}

###
DELETE {{LinkSharingRepository_HostAddress}}/users/delete
Content-Type: application/json

{
  "email": "chrisg@home.com",
  "password": "passowrd"
}
###
GET {{LinkSharingRepository_HostAddress}}/users/
Accept: application/json
###
Post {{LinkSharingRepository_HostAddress}}/customlinks/add
Content-Type: application/json

{
  "platformId": 1,
  "userId": 4,
  "linkUrl": "www.mylink.com"
}

###
GET {{LinkSharingRepository_HostAddress}}/customlinks/4
Accept: application/json

###
Get {{LinkSharingRepository_HostAddress}}/users/getauthenticateduser?username=chrisg@home.com&password=passowrd
Accept: application/json

